import { pgTable, uuid, text, timestamp, pgEnum, unique, index } from 'drizzle-orm/pg-core'
import { user } from './auth-schema'

/**
 * Application tables.
 *
 * `user`, `session`, `account` and `verification` are Better Auth's and live in
 * auth-schema.ts, generated by its CLI (`npx @better-auth/cli generate`) — do not
 * hand-edit that file; change the `user.additionalFields` config in src/lib/auth.ts
 * and regenerate. Everything Better Auth does not own belongs here.
 *
 * Two conventions from structure.md apply: tables are snake_case plural, and Drizzle
 * fields are camelCase mapping onto snake_case columns.
 *
 * PostGIS columns (zones.geometry) have no native Drizzle type and are added by a raw
 * SQL migration instead, then read and written through `sql` templates (ADR-011).
 * Zones arrive with the zone endpoints.
 */

export * from './auth-schema'

export const planEnum = pgEnum('plan', ['free', 'standard', 'premium'])

export const userPlans = pgTable(
  'user_plans',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    // text, not uuid: Better Auth issues its own string ids for `user.id`.
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    plan: planEnum('plan').notNull().default('free'),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    /** NULL = active indefinitely. Billing is not implemented; plans are assigned manually. */
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // One active plan row per user (tech.md models this 1:1).
    unique('user_plans_user_id_unique').on(t.userId),
    index('user_plans_user_id_idx').on(t.userId),
  ],
)

export type UserPlanRow = typeof userPlans.$inferSelect
