import { pgTable, uuid, text, timestamp, integer, numeric, pgEnum, unique, index } from 'drizzle-orm/pg-core'
import { user } from './auth-schema'

/**
 * Application tables.
 *
 * `user`, `session`, `account` and `verification` are Better Auth's and live in
 * auth-schema.ts, generated by its CLI (`npx @better-auth/cli generate`) — do not
 * hand-edit that file; change the `user.additionalFields` config in src/lib/auth.ts
 * and regenerate. Everything Better Auth does not own belongs here.
 *
 * Two conventions from structure.md apply: tables are snake_case plural, and Drizzle
 * fields are camelCase mapping onto snake_case columns.
 *
 * PostGIS columns (zones.geometry) have no native Drizzle type and are added by a raw
 * SQL migration instead, then read and written through `sql` templates (ADR-011).
 * Zones arrive with the zone endpoints.
 */

export * from './auth-schema'

export const planEnum = pgEnum('plan', ['free', 'standard', 'premium'])

export const userPlans = pgTable(
  'user_plans',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    // text, not uuid: Better Auth issues its own string ids for `user.id`.
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    plan: planEnum('plan').notNull().default('free'),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    /** NULL = active indefinitely. Billing is not implemented; plans are assigned manually. */
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // One active plan row per user (tech.md models this 1:1).
    unique('user_plans_user_id_unique').on(t.userId),
    index('user_plans_user_id_idx').on(t.userId),
  ],
)

export type UserPlanRow = typeof userPlans.$inferSelect

/** BR-020: chosen when the zone is created, and editable afterwards per BR-029. */
export const roadClassEnum = pgEnum('road_class', ['nasional', 'nasional_provinsi', 'semua'])

/** Whether the zone's capture windows are running. */
export const zoneStatusEnum = pgEnum('zone_status', ['collecting', 'paused'])

export const zones = pgTable(
  'zones',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    roadClass: roadClassEnum('road_class').notNull(),
    status: zoneStatusEnum('status').notNull().default('collecting'),

    // `geometry geometry(Polygon, 4326)` is added by migration 0002 — PostGIS has no
    // native Drizzle type, so it is written and read through `sql` templates with
    // ST_GeomFromGeoJSON / ST_AsGeoJSON (ADR-011). Declaring it here would make
    // drizzle-kit try to drop it on the next generate.

    /**
     * Segment count and total length inside the boundary for this road class.
     *
     * Nullable on purpose: they are derived from HERE, so an unconfigured HERE key
     * means "not known yet", which the UI renders as "—". Storing 0 would claim the
     * zone matched no roads, which is a different and wrong statement.
     */
    roadsCount: integer('roads_count'),
    lengthKm: numeric('length_km', { precision: 10, scale: 2 }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // BR-015 — zone names are unique per user.
    unique('zones_user_id_name_unique').on(t.userId, t.name),
    index('zones_user_id_idx').on(t.userId),
  ],
)

export type ZoneRow = typeof zones.$inferSelect
