import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

/**
 * Project rule: every timestamp column stores a time zone.
 *
 * A bare `timestamp(...)` in Drizzle is `timestamp WITHOUT time zone` — the value
 * carries no offset, so it means whatever the reading process assumes. That is
 * invisible while every container runs UTC and wrong the first time one does not,
 * and the failure is silent: no error, just times that are hours off.
 *
 * This is a source scan rather than a database or Drizzle-internals check on purpose.
 * The way this regresses in practice is `npx @better-auth/cli generate`, which
 * rewrites drizzle/auth-schema.ts and emits bare `timestamp(...)` every time. A source
 * scan catches that on the next `npm test`, before a migration is ever generated.
 */

const DRIZZLE_DIR = path.resolve(__dirname, '../../drizzle')

function schemaFiles(): string[] {
  return fs
    .readdirSync(DRIZZLE_DIR)
    .filter((f) => f.endsWith('.ts'))
    .map((f) => path.join(DRIZZLE_DIR, f))
}

/** `timestamp("created_at")` with no options object — the offending form. */
const BARE_TIMESTAMP = /timestamp\(\s*(['"])[a-z0-9_]+\1\s*\)/g

describe('every timestamp column carries a time zone', () => {
  it('finds schema files to check', () => {
    // Guards the guard: a rename that empties this list would make the suite pass
    // while checking nothing.
    const files = schemaFiles()
    expect(files.length).toBeGreaterThan(0)
    expect(files.some((f) => f.endsWith('auth-schema.ts'))).toBe(true)
  })

  it.each(schemaFiles())('%s uses withTimezone on every timestamp', (file) => {
    const source = fs.readFileSync(file, 'utf8')
    const offenders: string[] = []

    source.split('\n').forEach((line, i) => {
      BARE_TIMESTAMP.lastIndex = 0
      if (BARE_TIMESTAMP.test(line)) offenders.push(`  line ${i + 1}: ${line.trim()}`)
    })

    expect(
      offenders,
      `${path.basename(file)} has timestamp columns without a time zone:\n${offenders.join('\n')}\n\n` +
        `Add { withTimezone: true }. If this file was just regenerated by ` +
        `\`npx @better-auth/cli generate\`, re-apply it — the CLI drops it every time.`,
    ).toEqual([])
  })

  it('still detects the offending form, so the regex cannot rot silently', () => {
    const sample = `createdAt: timestamp("created_at").defaultNow().notNull(),`
    BARE_TIMESTAMP.lastIndex = 0
    expect(BARE_TIMESTAMP.test(sample)).toBe(true)

    const fixed = `createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),`
    BARE_TIMESTAMP.lastIndex = 0
    expect(BARE_TIMESTAMP.test(fixed)).toBe(false)
  })
})
